### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by Vlken** [mcheung63/netbeans-minimap#6]
Please make it synchronized with the scroll bar (like Code Outline).

**Comment by mcheung63** [comment]
what do you mean? when i scroll in editor, the minimap will effect.

**Comment by Vlken** [comment]
![img](https://cloud.githubusercontent.com/assets/26476328/24081287/3aeb78d8-0cb1-11e7-9ef5-2bb5605bef84.png) selected area is always below scroll bar level (in Code Outline is the same level)

**Comment by mcheung63** [comment]
Fixed, thanks so much for the bug report. Deployed the latest plugin to netbeans plugin central, and waiting for approval. Thanks again

**Comment by Chris2011** [comment]
I use the latest version 2.6, it is not fixed. Please reopen this ticket.

**Comment by Chris2011** [comment]
Still not fixed in version 2.8.
